sets_app/urls.py
from django.urls import path
from . import views

from django.urls import include

urlpatterns = [
    path('', views.menu, name='menu'),
]

urlpatterns += [
    #path('set/<uuid:pk>/new/', views.add_new_set, name='add-new-set'),
    # path('menu/', views.menu, name='menu'),
    path('set/new/', views.add_new_set, name='add-new-set'),
    path('rider/new/', views.add_new_rider, name='add-new-rider'),
    path('stats/', views.stats, name='stats'),
]

sidewake/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('sets_app/', include('sets_app.urls')),
]

# redirect root URL to the URL of our sets_app
urlpatterns += [
    path('menu/', RedirectView.as_view(url='sets_app/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

sets_app/models.py
from django.db import models

from django.urls import reverse

# Create your models here.

class Rider(models.Model):
    """Model representing a rider"""
    first_name = models.CharField(verbose_name="First name", max_length=100)
    last_name = models.CharField(verbose_name="Last name", max_length=100, default="Linavskis")
    nationality = models.CharField(verbose_name="Nationality", max_length=100, default="Latvia")
    date_of_birth = models.DateField(verbose_name="Birth date", default="04/01/1989")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"



class Boat(models.Model):
    """Model representing a boat"""

    brand = models.TextField(verbose_name="Brand of boat")
    model = models.TextField(verbose_name="Model of boat")
    date_added = models.DateField(verbose_name="Date boat was added to fleet")

    def __str__(self):
        return f"{self.brand} {self.model}"


class Set(models.Model):
    """Class defining set entry model"""

    date_time_entry = models.DateTimeField(
        verbose_name="DateTime of entry", auto_now_add=True
    )
    date_set = models.DateField(verbose_name="Date of set")
    duration = models.FloatField(verbose_name="Duration of set")
    driver = models.TextField(verbose_name="Name of driver")
    rider = models.ForeignKey(Rider, help_text="Select boat used for set", on_delete=models.SET_NULL, null=True)
    boat = models.ForeignKey(Boat, help_text="Select boat used for set", on_delete=models.SET_NULL, null=True)

    # Metadataoat
    class Meta:
        ordering = ['-date_set', 'boat']

    def get_absolute_url(self):
        """Returns the url to access a particular instance of the model."""
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return f"Day: {self.date_set} | Driver: {self.driver} | Rider: {self.rider} | Duration: {self.duration}min | Boat: {self.boat}"

sets_app/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from sets_app.models import Boat, Rider


class DateInput(forms.DateInput):
    input_type = 'date'


class AddSetForm(forms.Form):

    date_set = forms.DateField(widget=DateInput,
                               initial=str(datetime.date.today()),
                               help_text="Enter date of set.")

    # date_set = forms.DateField(
    #     help_text="Enter the date of the set.",
    #     required=True,
    #     label="Date of set",
    #     initial=str(datetime.date.today()),
    #     widget=forms.DateInput,
    # )

    duration = forms.FloatField(
        help_text="Enter duration of set.", required=True, label="Duration of set",
    )

    driver = forms.CharField(
        help_text="Enter name of driver.", required=True, label="Name of driver",
    )

    # TODO: check if rider exists in database
    rider = forms.CharField(
        help_text="Enter name of rider.", required=True, label="Name of rider",
    )

    boat = forms.ModelChoiceField(
        queryset=Boat.objects.all(),
        help_text="Enter boat used.",
        required=True,
        label="Boat",
    )

    def clean_duration(self):
        # getting clean data (using default validators)
        data = self.cleaned_data["duration"]

        # Check if duration is non-zero or negative value
        if data <= 0:
            raise ValidationError(
                _("Duration of set must be value larger than 0 minutes.")
            )

        # returning validated data
        return data

    def clean_rider(self):
        # TODO: check if rider exists in database, if not raise validationError
        data = self.cleaned_data["rider"]


class AddRiderModelFrom(ModelForm):

    class Meta:
        model = Rider
        fields = '__all__'
        # fields = 'first_name'
        # DOY = ('1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
        #        '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
        #        '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
        #        '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
        #        '2012', '2013', '2014', '2015')
        # widgets = {
        #     'date_of_birth': forms.SelectDateWidget(years=DOY)
        # }


    def clean_first_name(self):
        data = self.cleaned_data['first_name']

        # check if first name field is empty
        if data == "":
            raise ValidationError(_("Invalid empty entry for first name"))

        return data

    def clean_last_name(self):
        data = self.cleaned_data['last_name']

        # check if first name field is empty
        if data == "":
            raise ValidationError(_("Invalid empty entry for last name"))

        return data

sets_app/views.py
import datetime

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect

# models
from django.db.models import Sum, Count
from sets_app.models import Boat, Set
# forms
from sets_app.forms import AddSetForm, AddRiderModelFrom

@login_required
def index(request):
    """View function for home page of app"""

    # Generate counts for sets and boats
    num_sets = Set.objects.all().count()
    num_boats = Boat.objects.all().count()

    # Counting number of total minutes
    num_min = Set.objects.aggregate(Sum('duration'))['duration__sum']

    # aggregating all info into context variable
    context = {
        'num_sets': num_sets,
        'num_boats': num_boats,
        'num_mins': num_min,
    }

    return render(request, 'index.html', context=context)

@login_required
def menu(request):
    """View function for menu page"""

    context = {}
    return render(request, 'sets_app/menu_extended.html', context=context)

@login_required
def stats(request):
    """View function for stats page"""

    # query for all sets per boat
    query = list(Set.objects.values('boat_id').annotate(Sum('duration'), Count('id')))
    # getting boat ids from queries
    boat_ids = list(map(lambda d: d['boat_id'], query))
    boats = [Boat.objects.get(id=id_) for id_ in boat_ids]

    context = {
        'sets_query': query
    }

    return render(request, 'stats.html', context=context)


@login_required
def add_new_set(request):

    # if this is a POST request then process the form data
    if request.method == "POST":

        # create a AddSetForm form instance and populate it with data from teh request (binding)
        form = AddSetForm(request.POST)

        # check if form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data
            set_instance = Set(duration=form.cleaned_data["duration"],
                               driver=form.cleaned_data["driver"],
                               rider=form.cleaned_data["rider"],
                               boat=form.cleaned_data["boat"],
                               date_set=form.cleaned_data["date_set"])
            set_instance.save()

            # redirect to a new URL
            # TODO: add successfully added html page
            # return HttpResponseRedirect(reverse("set-added"))
            return HttpResponseRedirect(reverse("menu"))

    # if this is a GET request create a default form
    else:
        # can only read from db and not write to it - currently not implemented!
        form = AddSetForm()
        # set_instance = None

    context = {
        'form': form,
        # 'set_instance': set_instance,
    }

    return render(request, 'sets_app/add_set_form.html', context)
    # return render(request, 'sets_app/add_new_set.html', context)


@login_required
def add_new_rider(request):
    # if post request
    if request.method == "POST":
        form = AddRiderModelFrom(request.POST)
        # check if form is valid
        if form.is_valid():
            form.save(commit=True)

            return HttpResponseRedirect(reverse("menu"))
    # if get request
    else:
        # pass
        form = AddRiderModelFrom()
        # form.as_table()

    return render(request, 'sets_app/add_rider_form.html', {'form': form})
    # return render(request, 'sets_app/add_new_rider.html', {'form': form})

sets_app/templates/sets_app/add_new_rider.html
{% extends "base_template.html" %}

{% block content %}
<section id="cd-rider">
  <h1>Add New Rider</h1>
  <header class="cd-header">
    <div id="cd-logo"><a href="#0"><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/148866/cd-logo_2.svg" alt="Logo"></a></div>
    <a class="cd-menu-trigger" href="#main-nav">Menu<span></span></a>
  </header>

  <form id="cd-form" action="{% url 'add-new-rider' %}" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
</section>
{% endblock %}

sets_app/templates/sets_app/add_new_set.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Add New Set</h1>
    
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

sets_app/templates/sets_app/add_rider_form.html
{% extends "base_template.html" %}
{% load static %}
<!--<link rel="stylesheet" type="text/css" href="{% static 'css/menu/menu.css' %}"/>-->
{% block content %}
<!--<body>-->
<section id="cd-rider">
	<head>
	<title>Contact V3</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/form/icons/favicon.ico' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/util.css' %}">
<!--===============================================================================================-->
	</head>
	<header class="cd-header">
    <div id="cd-logo"><a href="#0"><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/148866/cd-logo_2.svg" alt="Logo"></a></div>
    <a class="cd-menu-trigger" href="#main-nav">Menu<span></span></a>
  	</header>
<!--	<div class="bg-contact3" style="background-image: url('images/menu_1.JPG');">-->
	<div class="bg-contact3">
<!--	<div class="bg-contact3" style="background-image: url({% static 'images/menu_1.JPG' %});">-->
		<div class="container-contact3">
			<div class="wrap-contact3">
				<form class="contact3-form validate-form" action="{% url 'add-new-rider' %}" method="post">
					{% csrf_token %}
					<span class="contact3-form-title">
						Add rider
					</span>

<!--					<div class="wrap-contact3-form-radio">-->
<!--						<div class="contact3-form-radio m-r-42">-->
<!--							<input class="input-radio3" id="radio1" type="radio" name="choice" value="say-hi" checked="checked">-->
<!--							<label class="label-radio3" for="radio1">-->
<!--								Say Hi-->
<!--							</label>-->
<!--						</div>-->

<!--						<div class="contact3-form-radio">-->
<!--							<input class="input-radio3" id="radio2" type="radio" name="choice" value="get-quote">-->
<!--							<label class="label-radio3" for="radio2">-->
<!--								Get Quote-->
<!--							</label>-->
<!--						</div>-->

<!--						<div class="contact3-form-radio">-->
<!--							<input class="input-radio3" id="radio3" type="radio" name="choice" value="get-quote">-->
<!--							<label class="label-radio3" for="radio3">-->
<!--								Get Some-->
<!--							</label>-->
<!--						</div>-->
<!--					</div>-->

					<div class="wrap-input3 validate-input" data-validate="First name is required">
						<label for="id_first_name"></label>
						<input class="input3" type="text" name="first_name" placeholder="Your First Name" required id="id_first_name">
						<span class="focus-input3"></span>
					</div>

					<div class="wrap-input3 validate-input" data-validate="Last name is required">
						<label for="id_last_name"></label>
						<input class="input3" type="text" name="last_name" placeholder="Your Last Name" required id="id_last_name">
						<span class="focus-input3"></span>
					</div>

					<div class="wrap-input3 validate-input" data-validate="Nationality is required">
						<label for="id_nationality"></label>
						<input class="input3" type="text" name="nationality" placeholder="Your Nationality" required id="id_nationality">
						<span class="focus-input3"></span>
					</div>

					<div class="wrap-input3 validate-input" data-validate="Date of birth is required">
						<label for="id_date_of_birth"></label>
						<input class="input3" type="text" name="date_of_birth" placeholder="Your Date of Birth (DD/MM/YYYY)" required id="id_date_of_birth">
						<span class="focus-input3"></span>
					</div>

<!--					<div class="wrap-input3 validate-input" data-validate = "Valid email is required: ex@abc.xyz">-->
<!--						<input class="input3" type="text" name="email" placeholder="Your Email">-->
<!--						<span class="focus-input3"></span>-->
<!--					</div>-->

<!--					<div class="wrap-input3 input3-select">-->
<!--						<div>-->
<!--							<select class="selection-2" name="service">-->
<!--								<option>Needed Services</option>-->
<!--								<option>eCommerce Bussiness</option>-->
<!--								<option>UI/UX Design</option>-->
<!--								<option>Online Services</option>-->
<!--							</select>-->
<!--						</div>-->
<!--						<span class="focus-input3"></span>-->
<!--					</div>-->

<!--					<div class="wrap-input3 input3-select">-->
<!--						<div>-->
<!--							<select class="selection-2" name="budget">-->
<!--								<option>Budget</option>-->
<!--								<option>1500 $</option>-->
<!--								<option>2000 $</option>-->
<!--								<option>3000 $</option>-->
<!--							</select>-->
<!--						</div>-->
<!--						<span class="focus-input3"></span>-->
<!--					</div>-->

<!--					<div class="wrap-input3 validate-input" data-validate = "Message is required">-->
<!--						<textarea class="input3" name="message" placeholder="Your Message"></textarea>-->
<!--						<span class="focus-input3"></span>-->
<!--					</div>-->

					<div class="container-contact3-form-btn">
						<button class="contact3-form-btn">
							Submit
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'javascript/form/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'javascript/form/bootstrap/popper.js' %}"></script>
	<script type="text/javascript" src="{% static 'javascript/form/bootstrap/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'javascript/form/select2/select2.min.js' %}"></script>
	<script>
		$(".selection-2").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});
	</script>
<!--===============================================================================================-->
<!--	<script src="js/main.js"></script>-->
    <script type="text/javascript" src="{% static 'javascript/menu.js' %}"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

</section>
{% endblock %}

sets_app/templates/sets_app/add_set_form.html
{% extends "base_template.html" %}
{% load static %}
<!--<link rel="stylesheet" type="text/css" href="{% static 'css/menu/menu.css' %}"/>-->
{% block content %}
<!--<body>-->
<section id="cd-set">
	<head>
	<title>Contact V3</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/form/icons/favicon.ico' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/form/util.css' %}">
<!--===============================================================================================-->
	</head>
	<header class="cd-header">
    <div id="cd-logo"><a href="#0"><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/148866/cd-logo_2.svg" alt="Logo"></a></div>
    <a class="cd-menu-trigger" href="#main-nav">Menu<span></span></a>
  	</header>
<!--	<div class="bg-contact3" style="background-image: url('images/menu_1.JPG');">-->
<!--	<div class="bg-contact3">-->
	<div class="bg-contact3" style="background-image: url({% static 'images/add_set.JPG' %});">
		<div class="container-contact3">
			<div class="wrap-contact3">
				<form class="contact3-form validate-form" action="{% url 'add-new-set' %}" method="post">
					{% csrf_token %}
					<span class="contact3-form-title">
						Add set
					</span>
<!--					<p><label for="id_date_set">Date set:</label> <input type="date" name="date_set" value="2020-05-03" required id="id_date_set"> <span class="helptext">Enter date of set.</span></p>\n-->
<!--					<p><label for="id_duration">Duration of set:</label> <input type="number" name="duration" step="any" required id="id_duration"> <span class="helptext">Enter duration of set.</span></p>\n-->
<!--					<p><label for="id_driver">Name of driver:</label> <input type="text" name="driver" required id="id_driver"> <span class="helptext">Enter name of driver.</span></p>\n-->
<!--					<p><label for="id_rider">Name of rider:</label> <input type="text" name="rider" required id="id_rider"> <span class="helptext">Enter name of rider.</span></p>\n-->
<!--					<p><label for="id_boat">Boat:</label> <select name="boat" required id="id_boat">\n  <option value="" selected>-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>\n\n  <option value="1">Mastercraft x22</option>\n\n  <option value="2">Mastercraft xstar</option>\n\n</select> <span class="helptext">Enter boat used.</span></p>-->

					<div class="wrap-input3 validate-input" data-validate="Date is required">
						<label for="id_date_set"></label>
						<input class="input3" type="date" name="date_set" value="2020-05-03" placeholder="Enter date of set" required id="id_date_set">
						<span class="focus-input3"></span>
					</div>

<!--					<input type="number" name="duration" step="any" required id="id_duration"> <span class="helptext">Enter duration of set.</span></p>\n-->
					<div class="wrap-input3 validate-input" data-validate="Duration is required">
						<label for="id_duration"></label>
						<input class="input3" type="number" name="duration" step="any" placeholder="Enter duration of set" required id="id_duration">
						<span class="focus-input3"></span>
					</div>

<!--					<input type="text" name="driver" required id="id_driver"> <span class="helptext">Enter name of driver.</span></p>\n-->
					<div class="wrap-input3 validate-input" data-validate="Nationality is required">
						<label for="id_driver"></label>
						<input class="input3" type="text" name="driver" placeholder="Enter driver" required id="id_driver">
						<span class="focus-input3"></span>
					</div>

<!--					<input type="text" name="rider" required id="id_rider"> <span class="helptext">Enter name of rider.</span></p>\n-->
					<div class="wrap-input3 validate-input" data-validate="Date of birth is required">
						<label for="id_rider"></label>
						<input class="input3" type="text" name="rider" placeholder="Enter rider" required id="id_rider">
						<span class="focus-input3"></span>
					</div>

<!--					<select name="boat" required id="id_boat">\n  <option value="" selected>-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>\n\n  <option value="1">Mastercraft x22</option>\n\n  <option value="2">Mastercraft xstar</option>\n\n</select> <span class="helptext">Enter boat used.</span></p>-->
					<div class="wrap-input3 validate-input" data-validate="Boat is required">
						<label for="id_boat"></label>
						<select name="boat" required id="id_boat">\n  <option value="" selected>---------</option>\n\n  <option value="1">Mastercraft x22</option>\n\n  <option value="2">Mastercraft xstar</option>\n\n</select>
						<span class="focus-input3"></span>
					</div>

					<div class="wrap-contact3-form-radio" data-validate="Boat is required">
<!--&lt;!&ndash;						<input class="input-radio3" type="text" name="rider" placeholder="Enter rider" required id="id_boat">&ndash;&gt;-->
<!--						<label for="id_boat"></label>-->
<!--						<div class="contact3-form-radio m-r-42">-->
<!--							<input class="input-radio3" id="radio1" type="radio" name="choice" value="1" checked="checked" required id="id_boat">-->
<!--							<label class="label-radio3" for="id_boat">-->
<!--								Mastercraft x22-->
<!--							</label>-->
<!--						</div>-->

<!--						<div class="contact3-form-radio">-->
<!--							<input class="input-radio3" id="radio2" type="radio" name="choice" value="2" required id="id_boat">-->
<!--							<label class="label-radio3" for="id_boat">-->
<!--								Mastercraft xstar-->
<!--							</label>-->
<!--						</div>-->
<!--					</div>-->

<!--					<div class="wrap-input3 validate-input" data-validate = "Valid email is required: ex@abc.xyz">-->
<!--						<input class="input3" type="text" name="email" placeholder="Your Email">-->
<!--						<span class="focus-input3"></span>-->
<!--					</div>-->

<!--					<div class="wrap-input3 input3-select">-->
<!--						<div>-->
<!--							<select class="selection-2" name="service">-->
<!--								<option>Needed Services</option>-->
<!--								<option>eCommerce Bussiness</option>-->
<!--								<option>UI/UX Design</option>-->
<!--								<option>Online Services</option>-->
<!--							</select>-->
<!--						</div>-->
<!--						<span class="focus-input3"></span>-->
<!--					</div>-->

<!--					<div class="wrap-input3 input3-select">-->
<!--						<div>-->
<!--							<select class="selection-2" name="budget">-->
<!--								<option>Budget</option>-->
<!--								<option>1500 $</option>-->
<!--								<option>2000 $</option>-->
<!--								<option>3000 $</option>-->
<!--							</select>-->
<!--						</div>-->
<!--						<span class="focus-input3"></span>-->
<!--					</div>-->

<!--					<div class="wrap-input3 validate-input" data-validate = "Message is required">-->
<!--						<textarea class="input3" name="message" placeholder="Your Message"></textarea>-->
<!--						<span class="focus-input3"></span>-->
<!--					</div>-->

					<div class="container-contact3-form-btn">
						<button class="contact3-form-btn">
							Submit
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'javascript/form/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'javascript/form/bootstrap/popper.js' %}"></script>
	<script type="text/javascript" src="{% static 'javascript/form/bootstrap/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'javascript/form/select2/select2.min.js' %}"></script>
	<script>
		$(".selection-2").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});
	</script>
<!--===============================================================================================-->
<!--	<script src="js/main.js"></script>-->
    <script type="text/javascript" src="{% static 'javascript/menu.js' %}"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

</section>
{% endblock %}

sets_app/templates/sets_app/menu.html
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}"/>
<script type="text/javascript" src="{% static 'javascript/menu.js' %}"></script>

<body>
<main id="cd-main-content">
	<section id="cd-intro">
		<h1>Sidewake Minutes</h1>

		<header class="cd-header">
			<div id="cd-logo"><a href="#0"><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/148866/cd-logo_2.svg" alt="Logo"></a></div>
			<a class="cd-menu-trigger" href="#main-nav">Menu<span></span></a>
		</header>
		<div class="cd-blurred-bg"></div>
	</section> <!-- cd-intro -->
</main>

<div class="cd-shadow-layer"></div>

<nav id="main-nav">
	<ul>
		<li><a href="{% url 'add-new-rider' %}"><span>Add Rider</span></a></li>
		<li><a href="{% url 'add-new-set' %}"><span>Add Set</span></a></li>
		<li><a href="#0"><span>Check profile</span></a></li>
		<li><a href="#0"><span>Fun facts</span></a></li>
		<li><a href="#0"><span>Contact us</span></a></li>
	</ul>
	<a href="#0" class="cd-close-menu">Close<span></span></a>
</nav>
</body>

sets_app/templates/sets_app/menu_extended.html
{% extends "base_template.html" %}

{% block content %}
<section id="cd-intro">
    <h1>Sidewake Minutes</h1>
    <header class="cd-header">
        <div id="cd-logo"><a href="#0"><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/148866/cd-logo_2.svg" alt="Logo"></a></div>
        <a class="cd-menu-trigger" href="#main-nav">Menu<span></span></a>
    </header>
    <div class="cd-blurred-bg"></div>
</section> <!-- cd-intro -->
{% endblock %}